from typing import List, Dict
from datetime import datetime
import io

class SQLGenerator:
    """
    Generator for creating SQL files with converted statements.
    Produces clean, well-formatted SQL output.
    """
    
    def __init__(self):
        pass
    
    def generate(
        self, 
        results: List[Dict], 
        source_dialect: str, 
        target_dialect: str,
        filename: str = None
    ) -> io.BytesIO:
        """
        Generate a SQL file with conversion results.
        
        Args:
            results: List of conversion results
            source_dialect: Source SQL dialect
            target_dialect: Target SQL dialect
            filename: Optional filename (for metadata)
            
        Returns:
            BytesIO buffer containing the SQL file
        """
        lines = []
        
        # Header comment block
        lines.append(self._create_header_block(source_dialect, target_dialect, len(results)))
        lines.append("")
        
        # Process each result
        success_count = 0
        error_count = 0
        
        for i, result in enumerate(results, 1):
            if result['status'] == 'success':
                success_count += 1
                lines.append(self._format_successful_conversion(i, result))
            else:
                error_count += 1
                lines.append(self._format_failed_conversion(i, result))
            
            lines.append("")  # Blank line between statements
        
        # Footer with summary
        lines.append(self._create_footer_block(success_count, error_count))
        
        # Join all lines
        content = "\n".join(lines)
        
        # Convert to bytes and return buffer
        buffer = io.BytesIO()
        buffer.write(content.encode('utf-8'))
        buffer.seek(0)
        
        return buffer
    
    def _create_header_block(
        self, 
        source_dialect: str, 
        target_dialect: str, 
        total_statements: int
    ) -> str:
        """Create the header comment block."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        header = f"""-- ============================================================================
-- SQL DIALECT CONVERSION RESULTS
-- ============================================================================
-- 
-- Source Dialect: {source_dialect}
-- Target Dialect: {target_dialect}
-- Total Statements: {total_statements}
-- Generated: {timestamp}
-- 
-- Generated by: SQL Where Clause Conversion Tool
-- 
-- ============================================================================"""
        
        return header
    
    def _format_successful_conversion(self, index: int, result: Dict) -> str:
        """Format a successfully converted statement."""
        original = result['original'].strip()
        converted = result['converted'].strip()
        notes = result.get('notes', '')
        
        # Ensure statements end with semicolon
        if not converted.endswith(';'):
            converted += ';'
        
        block = f"""-- ----------------------------------------------------------------------------
-- Statement {index} - CONVERTED SUCCESSFULLY
-- ----------------------------------------------------------------------------
-- Original:
-- {self._indent_sql(original, '--   ')}
--
-- Notes: {notes if notes else 'No notes'}
-- ----------------------------------------------------------------------------

{converted}"""
        
        return block
    
    def _format_failed_conversion(self, index: int, result: Dict) -> str:
        """Format a failed conversion."""
        original = result['original'].strip()
        error = result.get('notes', 'Unknown error')
        
        block = f"""-- ----------------------------------------------------------------------------
-- Statement {index} - CONVERSION FAILED
-- ----------------------------------------------------------------------------
-- Error: {error}
-- ----------------------------------------------------------------------------
-- Original Statement (could not be converted):
/*
{original}
*/"""
        
        return block
    
    def _indent_sql(self, sql: str, prefix: str) -> str:
        """Indent SQL with a prefix for comments."""
        lines = sql.split('\n')
        indented = [prefix + line if i > 0 else line for i, line in enumerate(lines)]
        return '\n'.join(indented)
    
    def _create_footer_block(self, success_count: int, error_count: int) -> str:
        """Create the footer summary block."""
        total = success_count + error_count
        success_rate = (success_count / total * 100) if total > 0 else 0
        
        footer = f"""-- ============================================================================
-- CONVERSION SUMMARY
-- ============================================================================
-- 
-- Total Statements Processed: {total}
-- Successfully Converted: {success_count}
-- Failed Conversions: {error_count}
-- Success Rate: {success_rate:.1f}%
-- 
-- ============================================================================
-- END OF CONVERSION RESULTS
-- ============================================================================"""
        
        return footer
